use_frameworks!

target 'AsyncMessagesViewController_Example' do
  pod 'AsyncMessagesViewController', :path => '../'

  target 'AsyncMessagesViewController_Tests' do
    inherit! :search_paths

    
  end
end
