platform :ios, '9.0'
use_frameworks!

target 'AsyncMessagesViewController_Example' do
  pod 'AsyncMessagesViewController', :path => '../'
  pod 'LoremIpsum'

  target 'AsyncMessagesViewController_Tests' do
    inherit! :search_paths
  end
end
